version: '3.8'

services:
  # Aplicación Next.js
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Para desarrollo: montar código fuente
      # - .:/app
      # - /app/node_modules
      # Para producción: usar imagen construida
      - ./public:/app/public:ro
    restart: unless-stopped
    networks:
      - app-network

  # Servicio de desarrollo (opcional)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: pnpm dev
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: